server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
